export interface ProductDataUpdate {
  product_name: string, 
  brand: string,
  model:string, 
  category:string, 
  description:string, 
  size:string, 
  color:string, 
  gender:string,
  purchase_price:number,
  sale_price:number,
  amount:string,
  photo:string,
  asset:boolean,
  material:string,
  supplier_name:string,
}